@echo off
ren "src\App.js" "App.jsx.tmp"
del "src\App.js"
ren "src\index.js" "main.jsx.tmp"
del "src\index.js"

ren "src\components\Footer\Footer.js" "Footer.jsx"
ren "src\components\Header\Header.js" "Header.jsx"
ren "src\components\ProblemIndexGraph\ProblemIndexGraph.js" "ProblemIndexGraph.jsx"
ren "src\components\ProblemLanguage\ProblemLanguage.js" "ProblemLanguage.jsx"
ren "src\components\ProblemRatingGraph\ProblemRatingGraph.js" "ProblemRatingGraph.jsx"
ren "src\components\ProblemTagsGraph\ProblemTagsGraph.js" "ProblemTagsGraph.jsx"
ren "src\components\ProblemVerdict\ProblemVerdict.js" "ProblemVerdict.jsx"
ren "src\components\RatingGraph\RatingGraph.js" "RatingGraph.jsx"
ren "src\components\UserBio\UserContest.js" "UserContest.jsx"
ren "src\components\UserBio\UserInfo.js" "UserInfo.jsx"
ren "src\components\VersusCommonContest\VersusCommonContest.js" "VersusCommonContest.jsx"
ren "src\components\VersusCommonContest\VersusCommonPie.js" "VersusCommonPie.jsx"
ren "src\components\VersusProblemIndexGraph\VersusProblemIndexGraph.js" "VersusProblemIndexGraph.jsx"
ren "src\components\VersusProblemRatingGraph\VersusProblemRatingGraph.js" "VersusProblemRatingGraph.jsx"
ren "src\components\VersusRatingGraph\VersusRatingGraph.js" "VersusRatingGraph.jsx"
ren "src\components\VersusSubmissionsCompare\VersusSubmissionsCompare.js" "VersusSubmissionsCompare.jsx"
ren "src\components\VersusUser\VersusUserContest.js" "VersusUserContest.jsx"
ren "src\components\VersusUser\VersusUserInfo.js" "VersusUserInfo.jsx"
ren "src\pages\SingleUser.js" "SingleUser.jsx"
ren "src\pages\Versus.js" "Versus.jsx"
